### PR TITLE
Completed volume detection

### PR DESCRIPTION
**Pull request by 0shine0**

### CODE REVIEW

**Comment by portokaliu** [comment]
All looks alright, my only inquiry would be how well it works in multiplayer. Do you foresee any issues?

**Comment by 0shine0** [comment]
There is an issue with multiplayer. I think it creates 2 sensor entities for some reason and only one gets destroyed when i want it to be destroyed. I will check whats the problem and resolve it.

**Comment by portokaliu** [comment]
Try getting 3 clients on the same server and see how many entities are created then. If 3, then you can deduce the source of the issue :)

**Comment by Cervator** [comment]
Merging this to both develop and then master for easier testing :-)

**Pull request merged**
